### ISSUE TITLE
Do not hardcode URLs to archive debs

### ISSUE THREAD

**Issue by evandandrea** [snapcrafters/brackets#1]
…as these are garbage collected regularly:
```
Pulling libgcrypt11-deb 
404 Client Error: Not Found for url: http://de.archive.ubuntu.com/ubuntu/pool/main/libg/libgcrypt11/libgcrypt11_1.5.3-2ubuntu4.4_amd64.deb
```

As libcrypt11 is only available in trusty, you need to build from source to handle this case.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/brackets/commit/a4fd15f80ecd3713cea67bf2aaca440c0a267fc0
