### ISSUE TITLE
Brackets installation fails

### ISSUE THREAD

**Issue by Veilleuse-00** [snapcrafters/brackets#11]
Hello.
Trying to install Brackets (Release 1.13.0-17696, 64-bit) with the deb file in Ubuntu 18.04 but it fails : it opens the App Center, asks me my password, and it looks like it's doing the job very fast but nothing is installed at all.

**Comment by flexiondotorg** [comment]
This issue tracker is for the snap, but the .deb. You can install the Brackets snap like this:

    snap install brackets --classic
