### ISSUE TITLE
snap outdated

### ISSUE THREAD

**Issue by kaincenteno** [snapcrafters/brackets#20]
Current version 1.14 has a bug that doesn’t show folder items on sidebar. Accourding to brackets github this was resolved on 1.14.2

See issue https://github.com/adobe/brackets/issues/14860 5

**Comment by popey** [comment]
It's not outdated for Linux. The upstream developers have not published a release for Linux. We consume the deb published by upstream. If they don't publish one, we have nothing to consume.

**Comment by kaincenteno** [comment]
got it. Thank you @popey  :cat: 

Will be closing this as it's not valid.
