### ISSUE TITLE
brackets stable 1.9 fails to launch

### ISSUE THREAD

**Issue by pixelr0** [snapcrafters/brackets#3]
i get this error "/snap/brackets/2/opt/brackets/brackets: error while loading shared libraries: libudev.so.0: cannot open shared object file: No such file or directory"

ubuntu 16.04, brackets 1.9 classic 
~$ snap info brackets
name:      brackets
summary:   "Brackets is a modern code editor for HTML, CSS and JavaScript."
publisher: snapcrafters
description: |
  Brackets is an open-source editor for web design and development
  built on top of web technologies such as HTML, CSS and JavaScript.
  The project was created and is maintained by Adobe, and is released
  under an MIT License.
  
commands:
  - brackets
tracking:    stable
installed:   1.9 (2) 142MB classic
refreshed:   2017-07-11 11:40:10 +0300 EEST
channels:              
  stable:    1.9  (2)  142MB classic
  candidate: 1.9  (2)  142MB classic
  beta:      1.9  (2)  142MB classic
  edge:      1.10 (10) 154MB classic

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/brackets/commit/2351279740e3daf9dca93fc415c02f32d5de46e5
