### ISSUE TITLE
Fonts not displaying properly on Ubuntu 18.04

### ISSUE THREAD

**Issue by gio-nadiradze** [snapcrafters/brackets#9]
I have Brackets on my Ubuntu 18.04 and fonts in menus are looking strange.

I changed the font from the theme editor, but the result is the same.

Here is a screenshot:
https://i.stack.imgur.com/IqbfX.png

also check askubuntu.com
https://askubuntu.com/questions/1030522/brackets-on-ubuntu-18-04-fonts-not-displaying-properly/1030563#1030563

**Comment by flexiondotorg** [comment]
Fixed via #15

**Comment by albert200000** [comment]
Having same issue in openSUSE 15.4. Any way to fix?
